### ISSUE TITLE
Compilierungsfehler

### ISSUE THREAD

**Issue by theoprivat** [ghost58400/esphome-udp-receiver#1]
Hallo, ich bekomme beim Kompilieren folgende Fehlermeldung, die mir absolut nichts sagt. Kann mir bitte jemand helfen ?
[udp-receiver-fehler.txt](https://github.com/ghost58400/esphome-udp-receiver/files/15458383/udp-receiver-fehler.txt)

Compiling .pioenvs/esph-smagoe-193/src/main.cpp.o
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/memory:83,
                 from src/esphome/components/socket/socket.h:2,
                 from src/esphome/components/api/api_frame_helper.h:14,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/unique_ptr.h: In instantiation of 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = UDP]':
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/unique_ptr.h:361:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = UDP; _Dp = std::default_delete<UDP>]'
src/esphome/components/udp_receiver/udp_receiver.h:14:7:   required from here
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/unique_ptr.h:83:16: error: invalid application of 'sizeof' to incomplete type 'UDP'
   83 |  static_assert(sizeof(_Tp)>0,

**Comment by ghost58400** [comment]
Hello, can you please post your esphome yaml file ?

**Comment by theoprivat** [comment]
Hello, I have to apologize that I haven't closed the issue yet. I built a UDP "sensor" myself.
Thanks for your help offered, greetings
